apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notifications-api
  template:
    metadata:
      labels:
        app: notifications-api
    spec:
      containers:
        - name: notifications-api
          image: joaopeu/notificationsapi:latest
          ports:
            - containerPort: 80
          env:
            - name: RABBITMQ__HOSTNAME
              value: "rabbitmq"
            - name: RABBITMQ__USERNAME
              value: "guest"
            - name: RABBITMQ__PASSWORD
              value: "guest"
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-api
spec:
  selector:
    app: notifications-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
